# vpath只能工作在原始请求为根路径的情况下，
# 当没有租户定制时把根下的请求重定位到"/appPath"下，
# 当存在租户定制时把根下的请求重定位到"/customFolder/appPath"下。

appPath="/acmis" # 静态网站的部署路径
appIndex="/login.html"  # 入口页面路径
defaultCustomFolder="/customization" # 所有网站租户的自定义文件夹默认存放在defaultCustomFolder下子文件夹中，子文件夹以租户的name命名。

# 如果没有在[[domains]]中设置租户，那么该租户不支持定制功能。
# 设置每个租户的域名、名字和定制文件夹，如果没有定制文件夹，那么默认为 <customFolder>/<name>
[[domains]]
domain='localhost' #西安仲裁委
name="xaac"
folder="/customization/xaac"

[[domains]]
domain="www.ahzx.com" #合肥仲裁委
name="ahzx"
folder="/customization/ahzx"

[[domains]]
domain="www.qzac.com" #钦州仲裁委
name="qzac"
folder="/customization/qzac"

# 测试：
# 1. 在使用默认文件夹和指定文件下两种情况下都返回了正确的内容。
# 2. 不改变现有acmis前端的部署，通过配置，直接在nginx中启动vpath，系统应该能正常运行。
# 3. 在蓝天仲裁委中尝试定制页面。