title = "vpath" # 虚拟服务器端文件路径的机制

port = "8081" # 端口

[defaultDir]
main="/folder" # 网站的根目录对应的文件夹。
custom="/customization" # 所有网站租户的自定义文件夹默认存放在custom_dir下子文件夹中，子文件夹以租户的name命名。
[defaultDir.appdir]
root = "/folder/mis" # 设置根应用路径，如果没有设置appdir."/"，那么默认设置为：<main>
# 设置子应用路径，如果没有设置appdir.xxx，那么默认设置为：<main>/xxx，
# 默认设置的含义是：没有设置子应用的路径视作根应用下的资源
mis = '/folder/mis'
front = '/folder/front'

[appDir]
root="/mis"
mis="/mis"
zcy="/zcy"

# 设置每个租户的域名和名字
# 如果没有在[[domains]]中设置租户，那么该租户不支持定制功能。
[[domains]]
domain='www.xaac.com'
name="xaac"
cn_name="西安仲裁委"

[[domains]]
domain="www.ahzx.com"
name="ahzx"
cn_name="合肥仲裁委"

[[domains]]
domain="www.qzac.com"
name="qzac"
cn_name="钦州仲裁委"

# 如果没有设置[customization.xxx]，那么默认xxx的dir设置为：<defaultDir.custom>/xxx
[customization.xaac]
dir="/customization/xaac"
[customization.xaac.appdir]
root="/customization/xaac/mis" # 如果没有设置appdir."/"，那么默认设置为：<dir>
# 如果没有设置appdir.xxx，那么默认设置为：<dir>/xxx ; 默认设置的含义是：没有设置子应用的路径视作根应用下的资源。
mis="/customization/xaac/mis"
zcy="/customization/xaac/zcy"

[customization.ahzx]
dir="/customization/ahzx"
[customization.ahzx.appdir]
root="/customization/ahzx/mis"
mis="/customization/ahzx/mis"
zcy="/customization/ahzx/zcy"

[customization.qzac]
dir="/customization/qzac"
[customization.qzac.appdir]
root="/customization/qzac/mis"
mis="/customization/qzac/mis"
zcy="/customization/qzac/zcy"

# 测试：
# 1. 列举上述配置文件中所设定的各种情况，验证返回了正确的内容。
# 2. 不改变现有前端的部署，通过配置，直接在nginx中启动vpath，系统应该能正常运行。
# 3. 在蓝天仲裁委中尝试定制页面。